name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 16
      uses: actions/setup-node@v4
      with:
        node-version: 16
    - run: yarn --frozen-lock
    - run: yarn build

  e2e:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 16
      uses: actions/setup-node@v4
      with:
        node-version: 16
    - run: yarn --frozen-lock
    - run: yarn test:e2e:ci
